name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get install -y libncurses-dev
    - name: configure
      run: chmod 0755 configure && mkdir build && cd build && $PWD/../configure
    - name: make
      run: cd build && make


#